"""Probe candidate YC/a16z-style startup ATS boards not already in sources.yml."""

from __future__ import annotations

import concurrent.futures as cf
import re
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES = ROOT / "config" / "sources.yml"

text = SOURCES.read_text(encoding="utf-8")
existing: set[tuple[str, str]] = set()
for match in re.finditer(r"adapter:\s*(\w+),\s*tenant:\s*([\w.-]+)", text):
    existing.add((match.group(1).lower(), match.group(2).lower()))

# Curated YC / a16z / Sequoia / Greylock-style startups to try (first-party ATS only).
CANDIDATES: list[tuple[str, str, str, str]] = [
    ("Resend", "resend.com", "ashby", "resend"),
    ("Cal.com", "cal.com", "ashby", "cal"),
    ("Cal.com", "cal.com", "ashby", "calcom"),
    ("PostHog", "posthog.com", "ashby", "posthog"),
    ("Expo", "expo.dev", "ashby", "expo"),
    ("Railway", "railway.app", "ashby", "railway"),
    ("Render", "render.com", "ashby", "render"),
    ("Fly.io", "fly.io", "ashby", "fly"),
    ("Fly.io", "fly.io", "ashby", "flyio"),
    ("Doppler", "doppler.com", "ashby", "doppler"),
    ("Statsig", "statsig.com", "ashby", "statsig"),
    ("Statsig", "statsig.com", "greenhouse", "statsig"),
    ("GrowthBook", "growthbook.io", "ashby", "growthbook"),
    ("Turso", "turso.tech", "ashby", "turso"),
    ("Convex", "convex.dev", "ashby", "convex"),
    ("Liveblocks", "liveblocks.io", "ashby", "liveblocks"),
    ("Instant", "instantdb.com", "ashby", "instant"),
    ("Instant", "instantdb.com", "ashby", "instantdb"),
    ("TigerBeetle", "tigerbeetle.com", "ashby", "tigerbeetle"),
    ("Inngest", "inngest.com", "ashby", "inngest"),
    ("Trigger.dev", "trigger.dev", "ashby", "triggerdev"),
    ("Trigger.dev", "trigger.dev", "ashby", "trigger"),
    ("Pipedream", "pipedream.com", "ashby", "pipedream"),
    ("Nango", "nango.dev", "ashby", "nango"),
    ("Temporal", "temporal.io", "greenhouse", "temporal"),
    ("Temporal", "temporal.io", "ashby", "temporal"),
    ("Prefect", "prefect.io", "ashby", "prefect"),
    ("Dagster", "dagster.io", "ashby", "dagster"),
    ("Airbyte", "airbyte.com", "ashby", "airbyte"),
    ("Hightouch", "hightouch.com", "ashby", "hightouch"),
    ("Metabase", "metabase.com", "lever", "metabase"),
    ("Hasura", "hasura.io", "ashby", "hasura"),
    ("Prisma", "prisma.io", "ashby", "prisma"),
    ("Sanity", "sanity.io", "ashby", "sanity"),
    ("Contentful", "contentful.com", "greenhouse", "contentful"),
    ("Mux", "mux.com", "ashby", "mux"),
    ("LiveKit", "livekit.io", "ashby", "livekit"),
    ("Stream", "getstream.io", "ashby", "getstream"),
    ("Ably", "ably.com", "ashby", "ably"),
    ("Netlify", "netlify.com", "ashby", "netlify"),
    ("Netlify", "netlify.com", "greenhouse", "netlify"),
    ("Docker", "docker.com", "ashby", "docker"),
    ("Docker", "docker.com", "greenhouse", "docker"),
    ("Wiz", "wiz.io", "ashby", "wiz"),
    ("Wiz", "wiz.io", "greenhouse", "wiz"),
    ("Snyk", "snyk.io", "greenhouse", "snyk"),
    ("Orca Security", "orca.security", "ashby", "orca"),
    ("Abnormal Security", "abnormalsecurity.com", "greenhouse", "abnormalsecurity"),
    ("Island", "island.io", "ashby", "island"),
    ("Drata", "drata.com", "ashby", "drata"),
    ("Secureframe", "secureframe.com", "ashby", "secureframe"),
    ("Bitwarden", "bitwarden.com", "ashby", "bitwarden"),
    ("Tailscale", "tailscale.com", "ashby", "tailscale"),
    ("Tailscale", "tailscale.com", "greenhouse", "tailscale"),
    ("Sourcegraph", "sourcegraph.com", "ashby", "sourcegraph"),
    ("Sourcegraph", "sourcegraph.com", "greenhouse", "sourcegraph"),
    ("Replit", "replit.com", "ashby", "replit"),
    ("Replit", "replit.com", "greenhouse", "replit"),
    ("Codeium", "codeium.com", "ashby", "codeium"),
    ("Windsurf", "windsurf.com", "ashby", "windsurf"),
    ("Exa", "exa.ai", "ashby", "exa"),
    ("Clay", "clay.com", "ashby", "clay"),
    ("Attio", "attio.com", "ashby", "attio"),
    ("Plain", "plain.com", "ashby", "plain"),
    ("Incident.io", "incident.io", "ashby", "incidentio"),
    ("Incident.io", "incident.io", "ashby", "incident"),
    ("Apollo.io", "apollo.io", "greenhouse", "apolloio"),
    ("Apollo.io", "apollo.io", "ashby", "apollo"),
    ("Groq", "groq.com", "ashby", "groq"),
    ("Groq", "groq.com", "greenhouse", "groq"),
    ("Cerebras", "cerebras.net", "greenhouse", "cerebras"),
    ("Fireworks AI", "fireworks.ai", "ashby", "fireworks"),
    ("Fireworks AI", "fireworks.ai", "ashby", "fireworksai"),
    ("Baseten", "baseten.co", "ashby", "baseten"),
    ("Fal", "fal.ai", "ashby", "fal"),
    ("Luma AI", "lumalabs.ai", "ashby", "lumalabs"),
    ("Ideogram", "ideogram.ai", "ashby", "ideogram"),
    ("Recraft", "recraft.ai", "ashby", "recraft"),
    ("Black Forest Labs", "bfl.ai", "ashby", "blackforestlabs"),
    ("Stability AI", "stability.ai", "ashby", "stabilityai"),
    ("Character.AI", "character.ai", "ashby", "character"),
    ("Character.AI", "character.ai", "greenhouse", "character"),
    ("Runway", "runwayml.com", "ashby", "runwayml"),
    ("Runway", "runwayml.com", "greenhouse", "runwayml"),
    ("Decagon", "decagon.ai", "ashby", "decagon"),
    ("Poolside", "poolside.ai", "ashby", "poolside"),
    ("Hebbia", "hebbia.com", "ashby", "hebbia"),
    ("Glean", "glean.com", "ashby", "glean"),
    ("Glean", "glean.com", "greenhouse", "glean"),
    ("Mercor", "mercor.com", "ashby", "mercor"),
    ("Parallel", "parallel.ai", "ashby", "parallel"),
    ("The Browser Company", "thebrowser.company", "ashby", "thebrowsercompany"),
    ("Arc", "arc.net", "ashby", "arc"),
    ("Descript", "descript.com", "greenhouse", "descript"),
    ("Gamma", "gamma.app", "ashby", "gamma"),
    ("Tome", "tome.app", "ashby", "tome"),
    ("Pitch", "pitch.com", "ashby", "pitch"),
    ("Brilliant", "brilliant.org", "ashby", "brilliant"),
    ("Quizlet", "quizlet.com", "lever", "quizlet"),
    ("Khan Academy", "khanacademy.org", "greenhouse", "khanacademy"),
    ("Hadrian", "hadrian.co", "ashby", "hadrian"),
    ("Saronic", "saronic.com", "ashby", "saronic"),
    ("Varda", "varda.com", "ashby", "varda"),
    ("Relativity Space", "relativityspace.com", "greenhouse", "relativityspace"),
    ("Nava", "navapbc.com", "greenhouse", "navapbc"),
    ("Snorkel AI", "snorkel.ai", "ashby", "snorkelai"),
    ("Labelbox", "labelbox.com", "greenhouse", "labelbox"),
    ("Lightning AI", "lightning.ai", "ashby", "lightning"),
    ("Lightning AI", "lightning.ai", "ashby", "lightningai"),
    ("Surge AI", "surge.ai", "ashby", "surgeai"),
    ("Surge AI", "surge.ai", "ashby", "surge"),
    ("Outlier", "outlier.ai", "ashby", "outlier"),
    ("Turing", "turing.com", "ashby", "turing"),
    ("AngelList", "angellist.com", "ashby", "angellist"),
    ("Wellfound", "wellfound.com", "ashby", "wellfound"),
    ("Y Combinator", "ycombinator.com", "ashby", "ycombinator"),
    ("Y Combinator", "ycombinator.com", "greenhouse", "ycombinator"),
    ("Flexport", "flexport.com", "greenhouse", "flexport"),
    ("GitHub", "github.com", "greenhouse", "github"),
    ("Kong", "konghq.com", "greenhouse", "kong"),
    ("Sentry", "sentry.io", "ashby", "sentry"),
    ("Raycast", "raycast.com", "ashby", "raycast"),
    ("Anysphere", "anysphere.co", "ashby", "anysphere"),
    ("Warp", "warp.dev", "ashby", "warp"),
    ("Fig", "fig.io", "ashby", "fig"),
    ("Dia", "diabrowser.com", "ashby", "dia"),
    ("Dia", "diabrowser.com", "ashby", "diabrowser"),
    ("You.com", "you.com", "ashby", "you"),
    ("You.com", "you.com", "ashby", "youcom"),
    ("Phind", "phind.com", "ashby", "phind"),
    ("Elicit", "elicit.com", "ashby", "elicit"),
    ("Otter.ai", "otter.ai", "ashby", "otter"),
    ("Otter.ai", "otter.ai", "greenhouse", "otterai"),
    ("Fireflies", "fireflies.ai", "ashby", "fireflies"),
    ("Grain", "grain.com", "ashby", "grain"),
    ("Fathom", "fathom.video", "ashby", "fathom"),
    ("Riverside", "riverside.fm", "ashby", "riverside"),
    ("Riverside", "riverside.fm", "ashby", "riversidefm"),
    ("Captions", "captions.ai", "ashby", "captions"),
    ("Captions", "captions.ai", "ashby", "captionsai"),
    ("Hippocratic AI", "hippocraticai.com", "ashby", "hippocraticai"),
    ("PathAI", "pathai.com", "greenhouse", "pathai"),
    ("Insitro", "insitro.com", "greenhouse", "insitro"),
    ("Tempus", "tempus.com", "greenhouse", "tempus"),
    ("Atomic Semi", "atomicsemi.com", "ashby", "atomicsemi"),
    ("Astera Labs", "asteralabs.com", "greenhouse", "asteralabs"),
    ("SambaNova", "sambanova.ai", "ashby", "sambanova"),
    ("SambaNova", "sambanova.ai", "greenhouse", "sambanova"),
    ("Tenstorrent", "tenstorrent.com", "ashby", "tenstorrent"),
    ("Tenstorrent", "tenstorrent.com", "greenhouse", "tenstorrent"),
    ("Lightmatter", "lightmatter.co", "ashby", "lightmatter"),
    ("Ayar Labs", "ayarlabs.com", "ashby", "ayarlabs"),
    ("PsiQuantum", "psiquantum.com", "ashby", "psiquantum"),
    ("IonQ", "ionq.com", "greenhouse", "ionq"),
    ("Rigetti", "rigetti.com", "greenhouse", "rigetti"),
    ("Quantinuum", "quantinuum.com", "ashby", "quantinuum"),
    ("Mistral AI", "mistral.ai", "ashby", "mistralai"),
    ("Mistral AI", "mistral.ai", "ashby", "mistral"),
    ("xAI", "x.ai", "ashby", "xai"),
    ("xAI", "x.ai", "greenhouse", "xai"),
    ("Adept", "adept.ai", "ashby", "adept"),
    ("Inflection", "inflection.ai", "ashby", "inflection"),
    ("Ada", "ada.cx", "ashby", "ada"),
    ("Forethought", "forethought.ai", "ashby", "forethought"),
    ("Observe.AI", "observe.ai", "ashby", "observe"),
    ("Observe.AI", "observe.ai", "ashby", "observeai"),
    ("Material Security", "material.security", "ashby", "materialsecurity"),
    ("Magic", "magic.dev", "ashby", "magic"),
    ("Magic", "magic.dev", "ashby", "magicdev"),
    ("Browser Use", "browser-use.com", "ashby", "browseruse"),
    ("Browser Use", "browser-use.com", "ashby", "browser-use"),
    ("MultiOn", "multion.ai", "ashby", "multion"),
    ("Consensus", "consensus.app", "ashby", "consensus"),
    ("Copy.ai", "copy.ai", "ashby", "copyai"),
    ("Jasper", "jasper.ai", "greenhouse", "jasperai"),
    ("Jasper", "jasper.ai", "ashby", "jasper"),
    ("Beautiful.ai", "beautiful.ai", "ashby", "beautifulai"),
    ("Streamlit", "streamlit.io", "ashby", "streamlit"),
    ("Streamlit", "streamlit.io", "greenhouse", "streamlit"),
    ("Gradio", "gradio.app", "ashby", "gradio"),
    ("Reflex", "reflex.dev", "ashby", "reflex"),
    ("Excalidraw", "excalidraw.com", "ashby", "excalidraw"),
    ("Epic Games", "epicgames.com", "greenhouse", "epicgames"),
    ("Riot Games", "riotgames.com", "greenhouse", "riotgames"),
    ("Niantic", "nianticlabs.com", "greenhouse", "niantic"),
    ("Drata", "drata.com", "greenhouse", "drata"),
    ("Secureframe", "secureframe.com", "greenhouse", "secureframe"),
    ("Lacework", "lacework.com", "greenhouse", "lacework"),
    ("Aqua Security", "aquasec.com", "greenhouse", "aquasecurity"),
    ("Isovalent", "isovalent.com", "ashby", "isovalent"),
    ("Solo.io", "solo.io", "ashby", "soloio"),
    ("Loft Labs", "loft.sh", "ashby", "loftlabs"),
    ("ReadySet", "readyset.io", "ashby", "readyset"),
    ("PeerDB", "peerdb.io", "ashby", "peerdb"),
    ("Astronomer", "astronomer.io", "greenhouse", "astronomer"),
    ("Prefect", "prefect.io", "greenhouse", "prefect"),
    ("Dagster", "dagster.io", "greenhouse", "dagster"),
    ("Airbyte", "airbyte.com", "greenhouse", "airbyte"),
    ("Hightouch", "hightouch.com", "greenhouse", "hightouch"),
    ("Census", "getcensus.com", "greenhouse", "census"),
    ("Census", "getcensus.com", "ashby", "getcensus"),
    ("Amplitude", "amplitude.com", "ashby", "amplitude"),
    ("Mixpanel", "mixpanel.com", "ashby", "mixpanel"),
    ("Postman", "postman.com", "ashby", "postman"),
    ("LaunchDarkly", "launchdarkly.com", "ashby", "launchdarkly"),
    ("Statsig", "statsig.com", "lever", "statsig"),
    ("GrowthBook", "growthbook.io", "greenhouse", "growthbook"),
    ("Doppler", "doppler.com", "greenhouse", "doppler"),
    ("Railway", "railway.app", "greenhouse", "railway"),
    ("Render", "render.com", "greenhouse", "render"),
    ("Expo", "expo.dev", "greenhouse", "expo"),
    ("PostHog", "posthog.com", "greenhouse", "posthog"),
    ("Resend", "resend.com", "greenhouse", "resend"),
    ("Cal.com", "cal.com", "greenhouse", "cal"),
    ("Cal.com", "cal.com", "greenhouse", "calcom"),
    ("Clerk", "clerk.com", "greenhouse", "clerk"),
    ("Vanta", "vanta.com", "greenhouse", "vanta"),
    ("Harvey", "harvey.ai", "greenhouse", "harvey"),
    ("ElevenLabs", "elevenlabs.io", "greenhouse", "elevenlabs"),
    ("Sierra", "sierra.ai", "greenhouse", "sierra"),
    ("Cognition", "cognition.ai", "greenhouse", "cognition"),
    ("Factory", "factory.ai", "greenhouse", "factory"),
    ("Browserbase", "browserbase.com", "greenhouse", "browserbase"),
    ("Pika", "pika.art", "greenhouse", "pika"),
    ("Writer", "writer.com", "greenhouse", "writer"),
    ("Tldraw", "tldraw.com", "greenhouse", "tldraw"),
    ("Abridge", "abridge.com", "greenhouse", "abridge"),
    ("Shield AI", "shield.ai", "greenhouse", "shieldai"),
    ("Anduril", "anduril.com", "greenhouse", "anduril"),
    ("Perplexity", "perplexity.ai", "greenhouse", "perplexity"),
    ("OpenAI", "openai.com", "greenhouse", "openai"),
    ("Anthropic", "anthropic.com", "greenhouse", "anthropic"),
    ("Scale AI", "scale.com", "lever", "scaleai"),
    ("Cohere", "cohere.com", "greenhouse", "cohere"),
    ("Hugging Face", "huggingface.co", "ashby", "huggingface"),
    ("Weights & Biases", "wandb.ai", "greenhouse", "wandb"),
    ("LangChain", "langchain.com", "greenhouse", "langchain"),
    ("Replicate", "replicate.com", "greenhouse", "replicate"),
    ("Together AI", "together.ai", "greenhouse", "togetherai"),
    ("Anyscale", "anyscale.com", "greenhouse", "anyscale"),
    ("Modal", "modal.com", "greenhouse", "modal"),
    ("Neon", "neon.tech", "greenhouse", "neon"),
    ("ClickHouse", "clickhouse.com", "greenhouse", "clickhouse"),
    ("Materialize", "materialize.com", "greenhouse", "materialize"),
    ("PlanetScale", "planetscale.com", "lever", "planetscale"),
    ("Retool", "retool.com", "greenhouse", "retool"),
    ("Linear", "linear.app", "greenhouse", "linear"),
    ("Notion", "notion.so", "greenhouse", "notion"),
    ("Figma", "figma.com", "ashby", "figma"),
    ("Vercel", "vercel.com", "lever", "vercel"),
    ("Supabase", "supabase.com", "greenhouse", "supabase"),
    ("Ramp", "ramp.com", "greenhouse", "ramp"),
    ("Mercury", "mercury.com", "lever", "mercury"),
    ("Rippling", "rippling.com", "greenhouse", "rippling"),
    ("Plaid", "plaid.com", "ashby", "plaid"),
    ("Brex", "brex.com", "ashby", "brex"),
    ("Deel", "deel.com", "greenhouse", "deel"),
    ("Remote", "remote.com", "greenhouse", "remote"),
    ("Gusto", "gusto.com", "ashby", "gusto"),
    ("Lattice", "lattice.com", "ashby", "lattice"),
    ("Culture Amp", "cultureamp.com", "ashby", "cultureamp"),
    ("Cursor", "cursor.com", "greenhouse", "cursor"),
    ("Hex", "hex.tech", "greenhouse", "hex"),
    ("Census", "getcensus.com", "ashby", "census"),
    ("Palantir", "palantir.com", "ashby", "palantir"),
    ("Databricks", "databricks.com", "ashby", "databricks"),
    ("Snowflake", "snowflake.com", "greenhouse", "snowflake"),
    ("Benchling", "benchling.com", "ashby", "benchling"),
    ("Recursion", "recursion.com", "ashby", "recursion"),
    ("Rocket Lab", "rocketlabusa.com", "ashby", "rocketlab"),
    ("SpaceX", "spacex.com", "ashby", "spacex"),
    ("Flatiron Health", "flatiron.com", "ashby", "flatironhealth"),
    ("Navan", "navan.com", "ashby", "navan"),
    ("Intercom", "intercom.com", "ashby", "intercom"),
    ("Loom", "loom.com", "ashby", "loom"),
    ("Canva", "canva.com", "ashby", "canva"),
    ("Airtable", "airtable.com", "ashby", "airtable"),
    ("Webflow", "webflow.com", "ashby", "webflow"),
    ("Framer", "framer.com", "greenhouse", "framer"),
    ("Zapier", "zapier.com", "ashby", "zapier"),
    ("Coda", "coda.io", "ashby", "coda"),
    ("Miro", "miro.com", "ashby", "miro"),
    ("Duolingo", "duolingo.com", "ashby", "duolingo"),
    ("Roblox", "roblox.com", "ashby", "roblox"),
    ("Unity", "unity.com", "ashby", "unity3d"),
    ("Discord", "discord.com", "ashby", "discord"),
    ("Twitch", "twitch.tv", "ashby", "twitch"),
    ("Reddit", "redditinc.com", "ashby", "reddit"),
    ("Dropbox", "dropbox.com", "ashby", "dropbox"),
    ("Airbnb", "airbnb.com", "ashby", "airbnb"),
    ("Lyft", "lyft.com", "ashby", "lyft"),
    ("DoorDash", "doordash.com", "ashby", "doordash"),
    ("Affirm", "affirm.com", "ashby", "affirm"),
    ("Block", "block.xyz", "ashby", "block"),
    ("Twilio", "twilio.com", "ashby", "twilio"),
    ("Asana", "asana.com", "ashby", "asana"),
    ("HubSpot", "hubspot.com", "ashby", "hubspot"),
    ("Okta", "okta.com", "ashby", "okta"),
    ("Auth0", "auth0.com", "ashby", "auth0"),
    ("Elastic", "elastic.co", "ashby", "elastic"),
    ("Grafana Labs", "grafana.com", "ashby", "grafanalabs"),
    ("Sentry", "sentry.io", "ashby", "getsentry"),
    ("PagerDuty", "pagerduty.com", "ashby", "pagerduty"),
    ("Splunk", "splunk.com", "ashby", "splunk"),
    ("Confluent", "confluent.io", "ashby", "confluent"),
    ("Cockroach Labs", "cockroachlabs.com", "ashby", "cockroachlabs"),
    ("Fivetran", "fivetran.com", "ashby", "fivetran"),
    ("dbt Labs", "getdbt.com", "ashby", "dbtlabs"),
    ("MongoDB", "mongodb.com", "ashby", "mongodb"),
    ("GitLab", "about.gitlab.com", "ashby", "gitlab"),
    ("Cloudflare", "cloudflare.com", "ashby", "cloudflare"),
    ("Datadog", "datadoghq.com", "ashby", "datadog"),
    ("Stripe", "stripe.com", "ashby", "stripe"),
    ("Coinbase", "coinbase.com", "ashby", "coinbase"),
    ("Robinhood", "robinhood.com", "ashby", "robinhood"),
    ("Chime", "chime.com", "ashby", "chime"),
    ("SoFi", "sofi.com", "ashby", "sofi"),
    ("Kraken", "kraken.com", "ashby", "kraken"),
    ("1Password", "1password.com", "greenhouse", "1password"),
    ("Wealthsimple", "wealthsimple.com", "greenhouse", "wealthsimple"),
    ("Faire", "faire.com", "ashby", "faire"),
    ("Instacart", "instacart.com", "ashby", "instacart"),
    ("Midjourney", "midjourney.com", "greenhouse", "midjourney"),
    ("Synthesia", "synthesia.io", "greenhouse", "synthesia"),
    ("Cresta", "cresta.com", "ashby", "cresta"),
    ("Astranis", "astranis.com", "ashby", "astranis"),
    ("Figure AI", "figure.ai", "ashby", "figure"),
    ("Figure AI", "figure.ai", "ashby", "figureai"),
    ("Figure AI", "figure.ai", "greenhouse", "figure"),
]


def url_for(adapter: str, tenant: str) -> str:
    if adapter == "greenhouse":
        return f"https://boards-api.greenhouse.io/v1/boards/{tenant}/jobs"
    if adapter == "ashby":
        return f"https://api.ashbyhq.com/posting-api/job-board/{tenant}"
    if adapter == "lever":
        return f"https://api.lever.co/v0/postings/{tenant}?mode=json"
    raise ValueError(adapter)


def probe(item: tuple[str, str, str, str]) -> tuple[str, str, str, str, int] | None:
    company, domain, adapter, tenant = item
    if (adapter, tenant) in existing:
        return None
    try:
        req = urllib.request.Request(
            url_for(adapter, tenant),
            headers={"User-Agent": "OpenRoleRadar/1.0"},
        )
        with urllib.request.urlopen(req, timeout=8) as resp:
            body = resp.read()
            if resp.status == 200 and len(body) > 40:
                return (company, domain, adapter, tenant, len(body))
    except (urllib.error.URLError, TimeoutError, ValueError):
        return None
    return None


def main() -> None:
    seen: set[tuple[str, str]] = set()
    unique: list[tuple[str, str, str, str]] = []
    for candidate in CANDIDATES:
        key = (candidate[2], candidate[3])
        if key in seen:
            continue
        seen.add(key)
        unique.append(candidate)

    hits: list[tuple[str, str, str, str, int]] = []
    with cf.ThreadPoolExecutor(max_workers=24) as executor:
        for result in executor.map(probe, unique):
            if result:
                hits.append(result)

    hits.sort(key=lambda row: row[0].lower())
    print(f"probed={len(unique)} already_seeded_skipped={sum(1 for c in unique if (c[2], c[3]) in existing)} new_live={len(hits)}")
    for company, domain, adapter, tenant, size in hits:
        print(
            f"- {{ company: {company}, domain: {domain}, adapter: {adapter}, tenant: {tenant} }}  # bytes={size}"
        )


if __name__ == "__main__":
    main()
